### ISSUE TITLE
Bug: Various new "griffe: Failed to parse annotation from 'BoolOp' node at file" errors

### ISSUE THREAD

**Issue by shaypal5** [mkdocstrings/griffe#104]
**Describe the bug**
My readthedocs-hosted mkdocs build worked fine up until [a recent commit](https://github.com/pdpipe/pdpipe/commit/b7120ef92a7af2ef3c976af34dd1a5fc815e136e) - which introduced a few numpy docstring syntax errors - where I started getting a lot of:
```griffe: Failed to parse annotation from 'BoolOp' node at pdpipe/cond.py:1```
for various files (always at line 1).

I have opened [Issue 102](https://github.com/mkdocstrings/griffe/issues/102) and there I was made aware of these bugs.

I then set down to thoroughly make sure my code was free of any numpy docstring errors. I settled on creating a workflow to recursively traverse the entire graph of defined objects in my package (classes, functions, class methods, etc.) and applying the [numpydoc validation functionality](https://numpydoc.readthedocs.io/en/latest/validation.html) to each of them. This was added as an automatic workflow run by Github Actions on every commit to my repository.

You can see the code implementing this here:
https://github.com/pdpipe/pdpipe/blob/master/dev/scripts/numpydoc_validate.py

I've started with a large number of erros (most of which are soft warnings which `mkdocs` works with - after all my docs compiled up until now), but some might be fatal to doc compilation:
https://github.com/pdpipe/pdpipe/actions/runs/3113775649/jobs/5048821098#step:5:1762
I've ended up with clean code:
https://github.com/pdpipe/pdpipe/actions/runs/3117898734/jobs/5056843342#step:5:10

*Note: I've chosen to ignore 5 types of errors:*
```python
HIDE_ERROR_CODES_LIST = [
    'ES01',  # No extended summary found
    'SA01',  # See Also section not found
    'EX01',  # No examples section found
]

SOFT_ERROR_CODES_LIST = HIDE_ERROR_CODES_LIST + [
    'SS06',  # Summary should fit in a single line
    'GL01',  # Docstring text (summary) should start in the line immediately
    # after the opening quotes (not in the same line, or leaving a blank line
    # in between)
]
```

*Note 2: I've fixed griffe and docstring_parser to the version they had on [my last successful readthedocs build](https://readthedocs.org/projects/pdpipe/builds/17662451/), which are:*

```bash
# specifically fixed deps by Shay
griffe==0.22.0
docstring_parser==0.14.1
```

**To Reproduce**
See full build here:
https://readthedocs.org/projects/pdpipe/builds/18158175/

And the repo here:
https://github.com/pdpipe/pdpipe

**Expected behavior**
Build should complete successfully.

**System (please complete the following information):**
- `griffe` version: griffe-0.22.0
- Python version: 3.8
- OS: Linux

**See full build here:**
https://readthedocs.org/projects/pdpipe/builds/18107492/

**Stacktrace**
```python
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/pdpipe/checkouts/latest/_build/html
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BinOp' node at pdpipe/basic_stages.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/basic_stages.py:1
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:99: Parameter 'exclude_columns' does not appear in the function signature
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BinOp' node at pdpipe/basic_stages.py:1
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:162: Parameter 'exclude_columns' does not appear in the function signature
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BoolOp' node at pdpipe/basic_stages.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BoolOp' node at pdpipe/basic_stages.py:1
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:511: Parameter 'exclude_columns' does not appear in the function signature
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/basic_stages.py:1
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:694: Parameter 'exclude_columns' does not appear in the function signature
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/col_generation.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BoolOp' node at pdpipe/cond.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BoolOp' node at pdpipe/cond.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BoolOp' node at pdpipe/core.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/core.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/core.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/core.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/core.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/core.py:1
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'Tuple' node at pdpipe/core.py:1
[31mERROR    -  [0mError reading page 'reference/cq.md': list index out of range
Traceback (most recent call last):
  File "/home/docs/.asdf/installs/python/3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/.asdf/installs/python/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocs/__main__.py", line 236, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings/extension.py", line 209, in _process_block
    rendered = handler.render(data, options)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings_handlers/python/handler.py", line 232, in render
    return template.render(
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/module.html", line 1, in top-level template code
    {% extends "_base/module.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/_base/module.html", line 58, in top-level template code
    {% include "children.html" with context %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/children.html", line 1, in top-level template code
    {% extends "_base/children.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/_base/children.html", line 45, in top-level template code
    {% include "class.html" with context %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/class.html", line 1, in top-level template code
    {% extends "_base/class.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/_base/class.html", line 72, in top-level template code
    <code>{% include "expression.html" with context %}</code>{% if not loop.last %}, {% endif %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
  File "/home/docs/.asdf/installs/python/3.10.4/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/griffe/dataclasses.py", line 142, in parsed
    return self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/griffe/dataclasses.py", line 155, in parse
    return parse(self, parser or self.parser, **(options or self.parser_options))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/griffe/docstrings/parsers.py", line 51, in parse
    return parsers[parser](docstring, **options)  # type: ignore[operator]
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/griffe/docstrings/numpy.py", line 687, in parse
    section, offset = reader(docstring, offset + 2, **options)  # type: ignore[operator]
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/griffe/docstrings/numpy.py", line 557, in _read_examples_section
    text, new_offset = _read_block(docstring, offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pdpipe/envs/latest/lib/python3.10/site-packages/griffe/docstrings/numpy.py", line 176, in _read_block
    if is_empty and new_offset < len(lines) + 1 and _is_dash_line(lines[new_offset + 2]):
IndexError: list index out of range
```

**Comment by shaypal5** [comment]
Note:

This is the full list of requirements version dependencies between the last working build and the failing one. If you have a clue or a hunch as to what might be the source of the new ``griffe`` errors, that would really help and my investigation.

Thank you! <3

![image](https://user-images.githubusercontent.com/917954/192092961-9228285a-36c7-4e70-bf22-4aa0289dc70a.png)

**Comment by pawamoy** [comment]
I just published version 0.22.2 which should fix these issues, could you try again with this version?

**Comment by shaypal5** [comment]
Yes! Trying right away!

**Comment by shaypal5** [comment]
Ok, this looks much cleaner and focused now:
```python
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/pdpipe/checkouts/latest/_build/html
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:99: Parameter 'exclude_columns' does not appear in the function signature
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:162: Parameter 'exclude_columns' does not appear in the function signature
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:511: Parameter 'exclude_columns' does not appear in the function signature
[33mWARNING  -  [0mgriffe: pdpipe/basic_stages.py:694: Parameter 'exclude_columns' does not appear in the function signature
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BoolOp' node at pdpipe/core.py:1
[31mERROR    -  [0mmkdocstrings: No module named 'pdp'
[31mERROR    -  [0mError reading page 'reference/runtime_parameters.md':
[31mERROR    -  [0mCould not collect 'pdp.run_time_parameters'

Aborted with a BuildError!
```

It helped me track down the last few bugs.
If resolving them does not fix the build I'll report back.

I'll report back either way, actually... :(

**Comment by shaypal5** [comment]
Done!

So this ended up going both ways:
The crashing bug has been in incorrect reference to `pdp` instead of `pdpipe`, but it seemed some unjustified errors (or just a confusing stacktrack) made it too hard to track the one actual bug.

Thank you so much for your help. Also, I've ended up with a numpy-docstring-linted project, so another win. :)

**Comment by shaypal5** [comment]
By the way, the successful build still had a single BoolOp error:
```python
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/pdpipe/checkouts/latest/_build/html
[31mERROR    -  [0mgriffe: Failed to parse annotation from 'BoolOp' node at pdpipe/core.py:1
INFO     -  Documentation built in 6.40 seconds
```

**Comment by pawamoy** [comment]
Thank you for reporting back! Great to see you've fixed most of your issues, and sorry for the troublesome debugging process :slightly_smiling_face: 
I'll take a look at the last BoolOp error message.
