### ISSUE TITLE
Infinite recursion, while loading `numpy` modules

### ISSUE THREAD

**Issue by aktech** [mkdocstrings/griffe#155]
**Describe the bug**

We're trying to use `griffe` in https://github.com/jupyter/papyri (See PR: https://github.com/jupyter/papyri/pull/250) to get structured function signatures. However we had a roadblock while loading numpy modules, we see infinite recursion.

**To Reproduce**

```python
In [1]: import griffe
   ...: griffe_numpy = griffe.load('numpy')
   ...: griffe_numpy.modules
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
Cell In[1], line 3
      1 import griffe
      2 griffe_numpy = griffe.load('numpy')
----> 3 griffe_numpy.modules

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:486, in Object.modules(self)
    479 @property
    480 def modules(self) -> dict[str, Module]:
    481     """Return the module members.
    482
    483     Returns:
    484         A dictionary of modules.
    485     """
--> 486     return {name: member for name, member in self.members.items() if member.kind is Kind.MODULE}

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:486, in <dictcomp>(.0)
    479 @property
    480 def modules(self) -> dict[str, Module]:
    481     """Return the module members.
    482
    483     Returns:
    484         A dictionary of modules.
    485     """
--> 486     return {name: member for name, member in self.members.items() if member.kind is Kind.MODULE}

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:861, in Alias.kind(self)
    859 # custom behavior to avoid raising exceptions
    860 try:
--> 861     return self.target.kind
    862 except (AliasResolutionError, CyclicAliasError):
    863     return Kind.ALIAS

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:1102, in Alias.target(self)
   1093 """Resolve and return the target, if possible.
   1094
   1095 Upon accessing this property, if the target is not already resolved,
   (...)
   1099     The resolved target.
   1100 """
   1101 if not self.resolved:
-> 1102     self.resolve_target()
   1103 return self._target

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:1143, in Alias.resolve_target(self)
   1141 self._passed_through = True
   1142 try:
-> 1143     self._resolve_target()
   1144 finally:
   1145     self._passed_through = False

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:1161, in Alias._resolve_target(self)
   1159 self._target = resolved
   1160 if self.parent is not None:
-> 1161     self._target.aliases[self.path] = self

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:954, in Alias.aliases(self)
    952 @property
    953 def aliases(self) -> dict[str, Alias]:  # noqa: D102
--> 954     return self.target.aliases

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:954, in Alias.aliases(self)
    952 @property
    953 def aliases(self) -> dict[str, Alias]:  # noqa: D102
--> 954     return self.target.aliases

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:1102, in Alias.target(self)
   1093 """Resolve and return the target, if possible.
   1094
   1095 Upon accessing this property, if the target is not already resolved,
   (...)
   1099     The resolved target.
   1100 """
   1101 if not self.resolved:
-> 1102     self.resolve_target()
   1103 return self._target

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:1143, in Alias.resolve_target(self)
   1141 self._passed_through = True
   1142 try:
-> 1143     self._resolve_target()
   1144 finally:
   1145     self._passed_through = False

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:1161, in Alias._resolve_target(self)
   1159 self._target = resolved
   1160 if self.parent is not None:
-> 1161     self._target.aliases[self.path] = self

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:954, in Alias.aliases(self)
    952 @property
    953 def aliases(self) -> dict[str, Alias]:  # noqa: D102
--> 954     return self.target.aliases

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:954, in Alias.aliases(self)
    952 @property
    953 def aliases(self) -> dict[str, Alias]:  # noqa: D102
--> 954     return self.target.aliases

    [... skipping similar frames: Alias.aliases at line 954 (2970 times)]

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:954, in Alias.aliases(self)
    952 @property
    953 def aliases(self) -> dict[str, Alias]:  # noqa: D102
--> 954     return self.target.aliases

File ~/miniconda3/envs/papyri/lib/python3.9/site-packages/griffe/dataclasses.py:1101, in Alias.target(self)
   1091 @property
   1092 def target(self) -> Object | Alias:
   1093     """Resolve and return the target, if possible.
   1094
   1095     Upon accessing this property, if the target is not already resolved,
   (...)
   1099         The resolved target.
   1100     """
-> 1101     if not self.resolved:
   1102         self.resolve_target()
   1103     return self._target

RecursionError: maximum recursion depth exceeded
```

**Expected behavior**
We expect to get modules instead of infinite recursion.

**Screenshots**

**System (please complete the following information):**
- `griffe` version: `0.27.1`
- Python version: `3.9.16`
- OS: MacOS

**Additional context**

Another question we wanted to ask: is there an easier way to load a module/function into griffe by using the imported instance of function, module?

**Comment by pawamoy** [comment]
Should be fixed in 0.27.3, let me know otherwise :slightly_smiling_face:

**Comment by aktech** [comment]
@pawamoy Thanks a lot! By the way is there an easier way to load a module/function into griffe by using the imported instance of function, module?

**Comment by aktech** [comment]
Seems like I can still reproduce this issue with `griffe==0.27.3`

**Comment by pawamoy** [comment]
What version of Numpy do you have?

**Comment by aktech** [comment]
> What version of Numpy do you have?

`numpy==1.24.2`

**Comment by pawamoy** [comment]
Thanks, I was able to replicate and fix the issue. I'll push a fix soon :slightly_smiling_face:

**Comment by aktech** [comment]
>Thanks, I was able to replicate and fix the issue. I'll push the fix soon 🙂

Awesome, thanks!

**Comment by pawamoy** [comment]
Will push a new release soon.
